image:
  repository: ghcr.io/youruser/agentic-proof-pack   # change me
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.example.com      # change me
      paths:
        - path: /
          pathType: Prefix
  tls: []                        # e.g. - secretName: api-tls; hosts: [api.example.com]

resources:
  requests: { cpu: "200m", memory: "256Mi" }
  limits:   { cpu: "1",    memory: "512Mi" }

env:
  APP_PORT: "8000"
  KB_DIR: "/app/data/knowledge_base"
  AUDIT_PATH: "/app/data/audit/audit.jsonl"
  AUTH_REQUIRED: "true"
  FAISS_ENABLED: "true"
  SVD_COMPONENTS: "128"
  ALLOWED_ORIGINS: "https://your-vercel-app.vercel.app"   # change me

secrets:
  AUDIT_SIGNING_KEY: "change-me-32chars"
  JWT_SECRET: "change-me-32chars"
  API_KEYS: ""                      # optional: comma-separated

persistence:
  enabled: false                    # set true + size if you want PV for /app/data

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
