apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentic-proof.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ include "agentic-proof.fullname" . }} }
  template:
    metadata:
      labels: { app: {{ include "agentic-proof.fullname" . }} }
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [ { name: http, containerPort: 8000 } ]
          envFrom:
            - configMapRef: { name: {{ include "agentic-proof.fullname" . }}-config }
            - secretRef:    { name: {{ include "agentic-proof.fullname" . }}-secret }
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
{{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
{{- end }}
      volumes:
{{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "agentic-proof.fullname" . }}-pvc
{{- end }}
