name: Helm Render

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Helm template
        run: |
          helm template agentic ./deploy/helm/agentic-proof \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/agentic-proof-pack \
            --set image.tag=latest \
            --set ingress.enabled=false \
            > rendered.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: helm-rendered
          path: rendered.yaml
